version: '3.9'

services:
  ppc-server:
    container_name: ppc-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ppc-server
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: 'mariadb:latest'
    container_name: kiosk-maria-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ../database/mysql/data:/var/lib/mysql

